twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    configOpenWeatherMapAppid: '%configOpenWeatherMapAppid%'
    configGoogleMapsApiKey: '%configGoogleMapsApiKey%'
    appVersion: 'v1.0.0'
